### ISSUE TITLE
Network Does Not Support ENS

### ISSUE THREAD

**Issue by arjunaskykok** [aave/protocol-v2#194]
I followed the guide in README. I got an error.

```bash
$ docker-compose run contracts-env npm run console:fork
> await run('aave:mainnet')
.... a lot of outputs ....
> run('set-DRE')
> const contractGetters = require('./helpers/contracts-getters');
> const lendingPool = await contractGetters.getLendingPool("LendingPool address from 'aave:mainnet' task");
undefined
> (node:30) UnhandledPromiseRejectionWarning: Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.1.2)
    at Logger.makeError (/src/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/src/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at EthersProviderWrapper.<anonymous> (/src/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1407:20)
    at step (/src/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/src/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/src/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5103)
(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by arjunaskykok** [comment]
I investigated this error.

So in one terminal, I executed `npx hardhat node`.

Then in another terminal I executed `npx hardhat dev:deploy-mock-tokens --network localhost`, `npx hardhat dev:deploy-address-provider --network localhost`, `npx hardhat dev:deploy-lending-pool --network localhost`, `npx hardhat dev:deploy-oracles --pool Aave --network localhost`, then finally in this command I encountered that error:
`npx hardhat dev:initialize-lending-pool --pool Aave  --network localhost`

**Comment by arjunaskykok** [comment]
This is the output of `npx hardhat dev:initialize-lending-pool --pool Aave --network localhost`:

![Selection_784](https://user-images.githubusercontent.com/32124593/126191948-faf8f2de-7ca0-4ecd-8761-bb6cc3038afa.png)

**Comment by aschmidt20** [comment]
When you run these two commands:

$ docker-compose run contracts-env npm run console:fork
> await run('aave:mainnet')

You should be able to deploy the contracts to a mainnet fork without running the commands individually. From your first screenshot it looks like you were able to get to this step. 

> const lendingPool = await contractGetters.getLendingPool("LendingPool address from 'aave:mainnet' task");

This command resulted in an ENS error because it's expecting an address to be passed as a parameter

**Comment by arjunaskykok** [comment]
Okay, thank you. Basically, I need to pass an address to `getLendingPool` method.

```const lendingPool = await contractGetters.getLendingPool("0xc3dd7a5CAC7EbAEa8356da9DE8E04ceFE7E5C075");```

I thought I had to paste the string verbatim. :)

Anyway, any idea how to fix the problem with running the commands individually. The problem is in `tasks/dev/5_initialize.ts` file or the `npx hardhat dev:initialize-lending-pool --pool Aave --network localhost` command. I wanted to deploy AAVE's protocol v2 to localhost network and let it live so I can interact it with another smart contract (flash loan, for example).

I can't do that with a mainnet fork console. When the console is up, where is the address of the mainnet fork network?
