### ISSUE TITLE
Cannot Deploy Reserves to Goerli Testnet

### ISSUE THREAD

**Issue by JaredChilders** [aave/protocol-v2#246]
This is error that is thrown by ethers.js, not the protocol-v2 codebase. but i'm not sure why the reserve deployments work for kovan and rinkeby, but not goerli. I configured everything in the markets and hardhat config. not sure what's wrong. The other contracts deploy just fine, its just the reserves that are having trouble deploying.

I'm getting the following error when trying to deploy Aave v2 contracts to Goerli Test network.
```
Error: resolver or addr is not configured for ENS name (argument="name", value="", code=INVALID_ARGUMENT, version=contracts/5.1.1)
    at Logger.makeError (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Logger.throwArgumentError (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
    at /home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/contracts/src.ts/index.ts:123:16
    at step (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/jaredchill/aave/protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'resolver or addr is not configured for ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: ''
}
```

 The error is thrown when calling `batchInitReserve()`:
![unknown](https://user-images.githubusercontent.com/9031951/142240013-b7f7c475-714a-4111-8a4c-ba34e08feecc.png)

The input into `batchInitReserve()` is:
```
[
  [
    {
      aTokenImpl: '0xdA6D3E52a58867Dc5F460C53812D23b0530005D2',
      stableDebtTokenImpl: '0xB430248B8a3D357B0e69b0dca96a7F2C4C571056',
      variableDebtTokenImpl: '0x53A3dC08b59E3f11aed91c32Ae0e37d4aB1d53B9',
      underlyingAssetDecimals: '18',
      interestRateStrategyAddress: '0xCe5c0c2bA7C0aE6DB748E9f5E7970278d19D2C7e',
      underlyingAsset: '0x21c8a148933e6ca502b47d729a485579c22e8a69',
      treasury: '',
      incentivesController: '0x0000000000000000000000000000000000000000',
      underlyingAssetName: 'DAI',
      aTokenName: 'Aave interest bearing DAI',
      aTokenSymbol: 'aDAI',
      variableDebtTokenName: 'Aave variable debt bearing DAI',
      variableDebtTokenSymbol: 'variableDebtDAI',
      stableDebtTokenName: 'Aave stable debt bearing DAI',
      stableDebtTokenSymbol: 'stableDebtDAI',
      params: '0x10'
    },
    {
      aTokenImpl: '0xdA6D3E52a58867Dc5F460C53812D23b0530005D2',
      stableDebtTokenImpl: '0xB430248B8a3D357B0e69b0dca96a7F2C4C571056',
      variableDebtTokenImpl: '0x53A3dC08b59E3f11aed91c32Ae0e37d4aB1d53B9',
      underlyingAssetDecimals: '6',
      interestRateStrategyAddress: '0xC479C51995EBDf5c48c862089f1C96A90bFf20B4',
      underlyingAsset: '0xde637d4c445ca2aae8f782ffac8d2971b93a4998',
      treasury: '',
      incentivesController: '0x0000000000000000000000000000000000000000',
      underlyingAssetName: 'USDC',
      aTokenName: 'Aave interest bearing USDC',
      aTokenSymbol: 'aUSDC',
      variableDebtTokenName: 'Aave variable debt bearing USDC',
      variableDebtTokenSymbol: 'variableDebtUSDC',
      stableDebtTokenName: 'Aave stable debt bearing USDC',
      stableDebtTokenSymbol: 'stableDebtUSDC',
      params: '0x10'
    },
    {
      aTokenImpl: '0xdA6D3E52a58867Dc5F460C53812D23b0530005D2',
      stableDebtTokenImpl: '0xB430248B8a3D357B0e69b0dca96a7F2C4C571056',
      variableDebtTokenImpl: '0x53A3dC08b59E3f11aed91c32Ae0e37d4aB1d53B9',
      underlyingAssetDecimals: '18',
      interestRateStrategyAddress: '0xC479C51995EBDf5c48c862089f1C96A90bFf20B4',
      underlyingAsset: '0x4884e2a214dc5040f52a41c3f21c765283170b6e',
      treasury: '',
      incentivesController: '0x0000000000000000000000000000000000000000',
      underlyingAssetName: 'USDT',
      aTokenName: 'Aave interest bearing USDT',
      aTokenSymbol: 'aUSDT',
      variableDebtTokenName: 'Aave variable debt bearing USDT',
      variableDebtTokenSymbol: 'variableDebtUSDT',
      stableDebtTokenName: 'Aave stable debt bearing USDT',
      stableDebtTokenSymbol: 'stableDebtUSDT',
      params: '0x10'
    },
    {
      aTokenImpl: '0xdA6D3E52a58867Dc5F460C53812D23b0530005D2',
      stableDebtTokenImpl: '0xB430248B8a3D357B0e69b0dca96a7F2C4C571056',
      variableDebtTokenImpl: '0x53A3dC08b59E3f11aed91c32Ae0e37d4aB1d53B9',
      underlyingAssetDecimals: '18',
      interestRateStrategyAddress: '0x82eff9B9d8089C3244f54bB1Cb21d3c004Adcb00',
      underlyingAsset: '0x60d4db9b534ef9260a88b0bed6c486fe13e604fc',
      treasury: '',
      incentivesController: '0x0000000000000000000000000000000000000000',
      underlyingAssetName: 'WETH',
      aTokenName: 'Aave interest bearing WETH',
      aTokenSymbol: 'aWETH',
      variableDebtTokenName: 'Aave variable debt bearing WETH',
      variableDebtTokenSymbol: 'variableDebtWETH',
      stableDebtTokenName: 'Aave stable debt bearing WETH',
      stableDebtTokenSymbol: 'stableDebtWETH',
      params: '0x10'
    }
  ]
]
```

and the contract that we're interacting with is [here](https://github.com/aave/protocol-v2/blob/c1ada1cb68bb26a39b6afdb299e58291b831f1ec/contracts/protocol/lendingpool/LendingPoolConfigurator.sol#L63).

I'm clueless to why its throwing this error, because it does not throw the error when deploying the contracts to rinkeby or kovan. Am I missing something?

**Comment by shivgupt** [comment]
1. The code snippet you shared from `init-helpers.ts` seems from a much older commit. Can you use master branch instead.
2. I would guess this issue is due to market's config. Can you share/check the market config files that you added [here](https://github.com/aave/protocol-v2/tree/master/markets)

**Comment by JaredChilders** [comment]
@shivgupt Yeah this is from an older commit, I was trying to modify some of the features in the aave v2 (I also changed some of the variables), so i didnt want to merge with master yet, as it might make things worse. but yes I can share the market config files with you.

**Comment by shivgupt** [comment]
Well I was suggesting to merge changes from master because some of the deployment script errors were fixed recently. 

You can share link to configs if your repo is public or dm on discord - shiv#0077
@JaredChilders
