### ISSUE TITLE
LendingPoolConfigurator initialize local deployment fails with "Invalid Address" Error

### ISSUE THREAD

**Issue by vibeshiftcapital** [aave/protocol-v2#281]
Having issues deploying locally with command:

`npx hardhat aave:dev --network buidlerevm_docker`

I get as far as deploying `DefaultReserveInterestRateStrategy` for all 21 test tokens and then get the following error when `batchInitReserve` is called for the first one:

```
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.0)
    at Logger.makeError (/Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.throwArgumentError (/Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
    at /Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/src.ts/index.ts:123:16
    at step (/Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/xxxxxxxx/xxxxxxxx/aave-protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/xxxxxxxx/xxxxxxxx/research/aave-protocol-v2/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'invalid address or ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: undefined
}
```

Running `npm run aave:evm:dev:migration` successfully compile and deploys but doesn't hit the local node I booted up to test with.

I'm assuming I'm getting `Invalid Address` because either a null or address from a different change is being sent to `batchInitReserve` but I can't find where this is happening.

Happy to provide more info if that helps.

Thank you!

**Comment by pranavkirtani** [comment]
any update on this issue? I am facing the same thing

**Comment by Ruben1987Alex** [comment]
I have the same Issue and searching. I hope somebody has an idea :)
